export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTARTION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const ITEM_ROUTE = '/item'
export const ABOUT_ROUTE = '/about'
export const CONTACTS_PAGE = '/contacts'